-- AlterTable
ALTER TABLE `property` ADD COLUMN `acType` VARCHAR(191) NULL,
    ADD COLUMN `builtArea` DOUBLE NULL,
    ADD COLUMN `chargesIncluded` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `configuration` VARCHAR(191) NULL,
    ADD COLUMN `depositMonths` INTEGER NULL,
    ADD COLUMN `elecCounter` VARCHAR(191) NULL,
    ADD COLUMN `gasCounter` VARCHAR(191) NULL,
    ADD COLUMN `heatingType` VARCHAR(191) NULL,
    ADD COLUMN `kitchenState` VARCHAR(191) NULL,
    ADD COLUMN `kitchenType` VARCHAR(191) NULL,
    ADD COLUMN `landArea` DOUBLE NULL,
    ADD COLUMN `nbBathrooms` INTEGER NULL,
    ADD COLUMN `nbLivingRooms` INTEGER NULL,
    ADD COLUMN `nbSuites` INTEGER NULL,
    ADD COLUMN `nbToilets` INTEGER NULL,
    ADD COLUMN `outdoorParking` INTEGER NULL,
    ADD COLUMN `parkingCount` INTEGER NULL,
    ADD COLUMN `rentalUsage` VARCHAR(191) NULL,
    ADD COLUMN `state` VARCHAR(191) NULL,
    ADD COLUMN `typology` VARCHAR(191) NULL,
    ADD COLUMN `usageType` VARCHAR(191) NULL,
    ADD COLUMN `waterCounter` VARCHAR(191) NULL;
