-- CreateTable
CREATE TABLE `partner_application` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyName` VARCHAR(191) NOT NULL,
    `contactName` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `category` ENUM('IMMOBILIER', 'HOTELLERIE', 'EVENEMENTIEL', 'ENTREPOSAGE') NULL,
    `subCategory` ENUM('AGENCE_IMMOBILIERE', 'PROMOTEUR_IMMOBILIER', 'HOTELLERIE_HEBERGEMENT', 'SALLE_DES_FETES', 'ENTREPOSAGE_FRIGORIFIQUE', 'ENTREPOSAGE_NON_FRIGORIFIQUE', 'ADMINISTRATEUR_BIENS', 'AUTRES_PROFESSIONNELS', 'HOTEL', 'COMPLEXE_TOURISTIQUE', 'VILLAGE_VACANCES', 'APPART_HOTEL', 'RESIDENCE_HOTELIERE', 'MOTEL', 'RELAIS_ROUTIER', 'CAMPING_TOURISTIQUE', 'AUTRES_STRUCTURES', 'SALLES_DINATOIRES', 'SALLE_FORMATION', 'SALLE_CONFERENCE', 'AUTRES_EVENEMENTIEL', 'AUTRES_ENTREPOSAGE_STOCKAGE') NULL,
    `websiteUrl` VARCHAR(191) NULL,
    `message` TEXT NULL,
    `logoUrl` VARCHAR(191) NULL,
    `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    `adminNote` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `reviewedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
