-- AlterTable
ALTER TABLE `user` ADD COLUMN `agreementNumber` VARCHAR(191) NULL,
    ADD COLUMN `commercialRegister` VARCHAR(191) NULL,
    ADD COLUMN `companyActivity` ENUM('AGENCE_IMMOBILIERE', 'PROMOTEUR_IMMOBILIER', 'HOTELLERIE_HEBERGEMENT', 'SALLE_DES_FETES', 'ENTREPOSAGE_FRIGORIFIQUE', 'ENTREPOSAGE_NON_FRIGORIFIQUE') NULL,
    ADD COLUMN `companyName` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    ADD COLUMN `townId` INTEGER NULL,
    ADD COLUMN `userType` ENUM('PARTICULIER', 'SOCIETE') NOT NULL DEFAULT 'PARTICULIER';
