-- AlterTable
ALTER TABLE `partner` ADD COLUMN `subCategory` ENUM('AGENCE_IMMOBILIERE', 'PROMOTEUR_IMMOBILIER', 'HOTELLERIE_HEBERGEMENT', 'SALLE_DES_FETES', 'ENTREPOSAGE_FRIGORIFIQUE', 'ENTREPOSAGE_NON_FRIGORIFIQUE', 'ADMINISTRATEUR_BIENS', 'AUTRES_PROFESSIONNELS', 'HOTEL', 'COMPLEXE_TOURISTIQUE', 'VILLAGE_VACANCES', 'APPART_HOTEL', 'RESIDENCE_HOTELIERE', 'MOTEL', 'RELAIS_ROUTIER', 'CAMPING_TOURISTIQUE', 'AUTRES_STRUCTURES', 'SALLES_DINATOIRES', 'SALLE_FORMATION', 'SALLE_CONFERENCE', 'AUTRES_EVENEMENTIEL', 'AUTRES_ENTREPOSAGE_STOCKAGE') NULL;

